# Generated by ariadne-codegen
# Source: graphql/ops.graphql

from typing import Any, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .input_types import TransactionQueryInput
from .mutation_send_raw_transaction import MutationSendRawTransaction
from .query_eth_syncing import QueryEthSyncing
from .query_metadata import QueryMetadata
from .query_transactions import QueryTransactions
from .query_usage_stat import QueryUsageStat
from .query_web_3_sha_3 import QueryWeb3Sha3


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def query_metadata(self, **kwargs: Any) -> QueryMetadata:
        query = gql(
            """
            query query_metadata {
              metadata {
                clientVersion
                chainId
                netVersion
                netListening
                netPeerCount
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="query_metadata", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return QueryMetadata.model_validate(data)

    async def query_eth_syncing(self, **kwargs: Any) -> QueryEthSyncing:
        query = gql(
            """
            query query_ethSyncing {
              ethSyncing
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="query_ethSyncing",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return QueryEthSyncing.model_validate(data)

    async def query_web_3_sha_3(self, message: str, **kwargs: Any) -> QueryWeb3Sha3:
        query = gql(
            """
            query query_web3Sha3($message: String!) {
              web3Sha3(message: $message)
            }
            """
        )
        variables: dict[str, object] = {"message": message}
        response = await self.execute(
            query=query, operation_name="query_web3Sha3", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return QueryWeb3Sha3.model_validate(data)

    async def query_transactions(
        self,
        input: Union[Optional[TransactionQueryInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> QueryTransactions:
        query = gql(
            """
            query query_transactions($input: TransactionQueryInput) {
              transactions(input: $input) {
                items {
                  blockNumber
                  txIndex
                  hash
                  fromAddress
                  toAddress
                  valueWei
                  gas
                  gasPrice
                  gasUsed
                  nonce
                  txType
                  maxFeePerGas
                  maxPriorityFeePerGas
                  input
                  success
                  logsCount
                  createdAt
                  logs {
                    blockNumber
                    txIndex
                    logIndex
                    txHash
                    blockHash
                    address
                    topics
                    data
                    removed
                    createdAt
                  }
                  internalTransactions {
                    blockNumber
                    txHash
                    traceIndex
                    traceAddress
                    fromAddress
                    toAddress
                    valueWei
                    callType
                    gas
                    gasUsed
                    input
                    output
                    error
                    success
                    createdAt
                  }
                }
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  totalCount
                  currentPage
                  totalPages
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="query_transactions",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return QueryTransactions.model_validate(data)

    async def query_usage_stat(self, **kwargs: Any) -> QueryUsageStat:
        query = gql(
            """
            query query_usageStat {
              usageStat {
                effectiveness
                jsonrpcRatio
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="query_usageStat", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return QueryUsageStat.model_validate(data)

    async def mutation_send_raw_transaction(
        self,
        signed_tx: Union[Optional[str], UnsetType] = UNSET,
        from_: Union[Optional[str], UnsetType] = UNSET,
        to: Union[Optional[str], UnsetType] = UNSET,
        value: Union[Optional[str], UnsetType] = UNSET,
        gas: Union[Optional[str], UnsetType] = UNSET,
        gas_price: Union[Optional[str], UnsetType] = UNSET,
        input: Union[Optional[str], UnsetType] = UNSET,
        nonce: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> MutationSendRawTransaction:
        query = gql(
            """
            mutation mutation_sendRawTransaction($signedTx: String, $from: String, $to: String, $value: String, $gas: String, $gasPrice: String, $input: String, $nonce: Int) {
              sendRawTransaction(
                signedTx: $signedTx
                from: $from
                to: $to
                value: $value
                gas: $gas
                gasPrice: $gasPrice
                input: $input
                nonce: $nonce
              )
            }
            """
        )
        variables: dict[str, object] = {
            "signedTx": signed_tx,
            "from": from_,
            "to": to,
            "value": value,
            "gas": gas,
            "gasPrice": gas_price,
            "input": input,
            "nonce": nonce,
        }
        response = await self.execute(
            query=query,
            operation_name="mutation_sendRawTransaction",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return MutationSendRawTransaction.model_validate(data)
