# Generated by ariadne-codegen
# Source: graphql

from typing import Any

from .async_base_client import AsyncBaseClient
from .mutation_send_raw_transaction import MutationSendRawTransaction
from .query_eth_syncing import QueryEthSyncing
from .query_metadata import QueryMetadata
from .query_transactions import QueryTransactions
from .query_usage_stat import QueryUsageStat
from .query_web_3_sha_3 import QueryWeb3Sha3


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def query_metadata(self, **kwargs: Any) -> QueryMetadata:
        query = gql(
            """
            query query_metadata {
              metadata {
                clientVersion
                chainId
                netVersion
                netListening
                netPeerCount
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="query_metadata", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return QueryMetadata.model_validate(data)

    async def query_eth_syncing(self, **kwargs: Any) -> QueryEthSyncing:
        query = gql(
            """
            query query_ethSyncing {
              ethSyncing
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="query_ethSyncing",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return QueryEthSyncing.model_validate(data)

    async def query_web_3_sha_3(self, message: str, **kwargs: Any) -> QueryWeb3Sha3:
        query = gql(
            """
            query query_web3Sha3($message: String!) {
              web3Sha3(message: $message)
            }
            """
        )
        variables: dict[str, object] = {"message": message}
        response = await self.execute(
            query=query, operation_name="query_web3Sha3", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return QueryWeb3Sha3.model_validate(data)

    async def query_transactions(self, **kwargs: Any) -> QueryTransactions:
        query = gql(
            """
            query query_transactions {
              transactions {
                items {
                  blockNumber
                  txIndex
                  hash
                  fromAddress
                  toAddress
                  valueWei
                  gas
                  gasPrice
                  gasUsed
                  nonce
                  txType
                  maxFeePerGas
                  maxPriorityFeePerGas
                  input
                  success
                  logsCount
                  createdAt
                  logs {
                    blockNumber
                    txIndex
                    logIndex
                    txHash
                    blockHash
                    address
                    topics
                    data
                    removed
                    createdAt
                  }
                  internalTransactions {
                    blockNumber
                    txHash
                    traceIndex
                    traceAddress
                    fromAddress
                    toAddress
                    valueWei
                    callType
                    gas
                    gasUsed
                    input
                    output
                    error
                    success
                    createdAt
                  }
                }
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  totalCount
                  currentPage
                  totalPages
                }
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="query_transactions",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return QueryTransactions.model_validate(data)

    async def query_usage_stat(self, **kwargs: Any) -> QueryUsageStat:
        query = gql(
            """
            query query_usageStat {
              usageStat {
                effectiveness
                jsonrpcRatio
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="query_usageStat", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return QueryUsageStat.model_validate(data)

    async def mutation_send_raw_transaction(
        self, **kwargs: Any
    ) -> MutationSendRawTransaction:
        query = gql(
            """
            mutation mutation_sendRawTransaction {
              sendRawTransaction
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="mutation_sendRawTransaction",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return MutationSendRawTransaction.model_validate(data)
