# Generated by ariadne-codegen
# Source: http://localhost:8000/anvil/graphql

from enum import Enum


class TransactionOrderField(str, Enum):
    BLOCK_NUMBER = "BLOCK_NUMBER"
    TX_INDEX = "TX_INDEX"
    HASH = "HASH"
    FROM_ADDRESS = "FROM_ADDRESS"
    TO_ADDRESS = "TO_ADDRESS"
    VALUE_WEI = "VALUE_WEI"
    GAS = "GAS"
    GAS_PRICE = "GAS_PRICE"
    GAS_USED = "GAS_USED"
    NONCE = "NONCE"
    CREATED_AT = "CREATED_AT"


class SortDirection(str, Enum):
    ASC = "ASC"
    DESC = "DESC"
