# Generated by ariadne-codegen
# Source: http://localhost:8000/anvil/graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SortDirection, TransactionOrderField


class TransactionQueryInput(BaseModel):
    filters: Optional["TransactionFilterInput"] = None
    pagination: Optional["PaginationInput"] = None
    order_by: Optional[list["TransactionOrderByInput"]] = Field(
        alias="orderBy", default=None
    )


class TransactionFilterInput(BaseModel):
    hash: Optional["StringFilter"] = None
    from_address: Optional["StringFilter"] = Field(alias="fromAddress", default=None)
    to_address: Optional["StringFilter"] = Field(alias="toAddress", default=None)
    input: Optional["StringFilter"] = None
    block_number: Optional["IntFilter"] = Field(alias="blockNumber", default=None)
    tx_index: Optional["IntFilter"] = Field(alias="txIndex", default=None)
    nonce: Optional["IntFilter"] = None
    tx_type: Optional["IntFilter"] = Field(alias="txType", default=None)
    logs_count: Optional["IntFilter"] = Field(alias="logsCount", default=None)
    value_wei: Optional["BigIntFilter"] = Field(alias="valueWei", default=None)
    gas: Optional["BigIntFilter"] = None
    gas_price: Optional["BigIntFilter"] = Field(alias="gasPrice", default=None)
    gas_used: Optional["BigIntFilter"] = Field(alias="gasUsed", default=None)
    max_fee_per_gas: Optional["BigIntFilter"] = Field(
        alias="maxFeePerGas", default=None
    )
    max_priority_fee_per_gas: Optional["BigIntFilter"] = Field(
        alias="maxPriorityFeePerGas", default=None
    )
    success: Optional["BoolFilter"] = None
    created_at: Optional["DateTimeFilter"] = Field(alias="createdAt", default=None)
    and_: Optional[list["TransactionFilterInput"]] = Field(alias="and", default=None)
    or_: Optional[list["TransactionFilterInput"]] = Field(alias="or", default=None)
    not_: Optional["TransactionFilterInput"] = Field(alias="not", default=None)


class StringFilter(BaseModel):
    eq: Optional[str] = None
    ne: Optional[str] = None
    contains: Optional[str] = None
    not_contains: Optional[str] = Field(alias="notContains", default=None)
    starts_with: Optional[str] = Field(alias="startsWith", default=None)
    ends_with: Optional[str] = Field(alias="endsWith", default=None)
    regex: Optional[str] = None
    not_regex: Optional[str] = Field(alias="notRegex", default=None)
    in_: Optional[list[str]] = Field(alias="in", default=None)
    not_in: Optional[list[str]] = Field(alias="notIn", default=None)
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class IntFilter(BaseModel):
    eq: Optional[int] = None
    ne: Optional[int] = None
    gt: Optional[int] = None
    gte: Optional[int] = None
    lt: Optional[int] = None
    lte: Optional[int] = None
    in_: Optional[list[int]] = Field(alias="in", default=None)
    not_in: Optional[list[int]] = Field(alias="notIn", default=None)
    between: Optional[list[int]] = None
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class BigIntFilter(BaseModel):
    eq: Optional[str] = None
    ne: Optional[str] = None
    gt: Optional[str] = None
    gte: Optional[str] = None
    lt: Optional[str] = None
    lte: Optional[str] = None
    in_: Optional[list[str]] = Field(alias="in", default=None)
    not_in: Optional[list[str]] = Field(alias="notIn", default=None)
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class BoolFilter(BaseModel):
    eq: Optional[bool] = None
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class DateTimeFilter(BaseModel):
    eq: Optional[Any] = None
    ne: Optional[Any] = None
    gt: Optional[Any] = None
    gte: Optional[Any] = None
    lt: Optional[Any] = None
    lte: Optional[Any] = None
    between: Optional[list[Any]] = None
    is_null: Optional[bool] = Field(alias="isNull", default=None)


class PaginationInput(BaseModel):
    limit: int
    offset: int


class TransactionOrderByInput(BaseModel):
    field: TransactionOrderField
    direction: SortDirection


TransactionQueryInput.model_rebuild()
TransactionFilterInput.model_rebuild()
