# Generated by ariadne-codegen
# Source: graphql

from pydantic import Field

from .base_model import BaseModel


class MutationSendRawTransaction(BaseModel):
    send_raw_transaction: str = Field(alias="sendRawTransaction")
