# Generated by ariadne-codegen
# Source: graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryMetadata(BaseModel):
    metadata: "QueryMetadataMetadata"


class QueryMetadataMetadata(BaseModel):
    client_version: Optional[str] = Field(alias="clientVersion")
    chain_id: Optional[str] = Field(alias="chainId")
    net_version: Optional[str] = Field(alias="netVersion")
    net_listening: Optional[bool] = Field(alias="netListening")
    net_peer_count: Optional[str] = Field(alias="netPeerCount")


QueryMetadata.model_rebuild()
