# Generated by ariadne-codegen
# Source: graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class QueryEthSyncing(BaseModel):
    eth_syncing: Optional[Any] = Field(alias="ethSyncing")
