# Generated by ariadne-codegen
# Source: graphql/ops.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryTransactions(BaseModel):
    transactions: Optional["QueryTransactionsTransactions"]


class QueryTransactionsTransactions(BaseModel):
    items: list["QueryTransactionsTransactionsItems"]
    page_info: "QueryTransactionsTransactionsPageInfo" = Field(alias="pageInfo")


class QueryTransactionsTransactionsItems(BaseModel):
    block_number: Optional[str] = Field(alias="blockNumber")
    tx_index: Optional[str] = Field(alias="txIndex")
    hash: Optional[str]
    from_address: Optional[str] = Field(alias="fromAddress")
    to_address: Optional[str] = Field(alias="toAddress")
    value_wei: Optional[str] = Field(alias="valueWei")
    gas: Optional[str]
    gas_price: Optional[str] = Field(alias="gasPrice")
    gas_used: Optional[str] = Field(alias="gasUsed")
    nonce: Optional[str]
    tx_type: Optional[str] = Field(alias="txType")
    max_fee_per_gas: Optional[str] = Field(alias="maxFeePerGas")
    max_priority_fee_per_gas: Optional[str] = Field(alias="maxPriorityFeePerGas")
    input: Optional[str]
    success: Optional[bool]
    logs_count: Optional[str] = Field(alias="logsCount")
    created_at: Optional[str] = Field(alias="createdAt")
    logs: list["QueryTransactionsTransactionsItemsLogs"]
    internal_transactions: list[
        "QueryTransactionsTransactionsItemsInternalTransactions"
    ] = Field(alias="internalTransactions")


class QueryTransactionsTransactionsItemsLogs(BaseModel):
    block_number: Optional[str] = Field(alias="blockNumber")
    tx_index: Optional[str] = Field(alias="txIndex")
    log_index: Optional[str] = Field(alias="logIndex")
    tx_hash: Optional[str] = Field(alias="txHash")
    block_hash: Optional[str] = Field(alias="blockHash")
    address: Optional[str]
    topics: Optional[list[str]]
    data: Optional[str]
    removed: Optional[bool]
    created_at: Optional[str] = Field(alias="createdAt")


class QueryTransactionsTransactionsItemsInternalTransactions(BaseModel):
    block_number: Optional[str] = Field(alias="blockNumber")
    tx_hash: Optional[str] = Field(alias="txHash")
    trace_index: Optional[str] = Field(alias="traceIndex")
    trace_address: Optional[str] = Field(alias="traceAddress")
    from_address: Optional[str] = Field(alias="fromAddress")
    to_address: Optional[str] = Field(alias="toAddress")
    value_wei: Optional[str] = Field(alias="valueWei")
    call_type: Optional[str] = Field(alias="callType")
    gas: Optional[str]
    gas_used: Optional[str] = Field(alias="gasUsed")
    input: Optional[str]
    output: Optional[str]
    error: Optional[str]
    success: Optional[bool]
    created_at: Optional[str] = Field(alias="createdAt")


class QueryTransactionsTransactionsPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    total_count: int = Field(alias="totalCount")
    current_page: int = Field(alias="currentPage")
    total_pages: int = Field(alias="totalPages")


QueryTransactions.model_rebuild()
QueryTransactionsTransactions.model_rebuild()
QueryTransactionsTransactionsItems.model_rebuild()
