# Generated by ariadne-codegen
# Source: graphql

from pydantic import Field

from .base_model import BaseModel


class QueryUsageStat(BaseModel):
    usage_stat: "QueryUsageStatUsageStat" = Field(alias="usageStat")


class QueryUsageStatUsageStat(BaseModel):
    effectiveness: float
    jsonrpc_ratio: float = Field(alias="jsonrpcRatio")


QueryUsageStat.model_rebuild()
