# Generated by ariadne-codegen
# Source: graphql/ops.graphql

from pydantic import Field

from .base_model import BaseModel


class QueryWeb3Sha3(BaseModel):
    web_3_sha_3: str = Field(alias="web3Sha3")
